
name: Build and Deploy

env:
  APP_NAME: pict

on:
  push:
    branch:
      - master

jobs:
  deploy:
    name: Build dockerfile and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
				docker build . --file Dockerfile \
					--tag $APP_NAME:latest --tag $APP_NAME:${{ github.sha }}
        docker save $APP_NAME:latest | gzip > image.tar.gz
    - name: Deploy Docker image
      shell: bash
      env:
        SSH_HOST: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
      run: |
        echo "${{ secrets.SSH_KEY }}" > ./key
        chmod 0600 ./key
        scp -o StrictHostKeyChecking=no -i ./key \
          image.tar.gz $SSH_HOST:images/$APP_NAME.tar.gz
        ssh -o StrictHostKeyChecking=no -i ./key $SSH_HOST \
          'bash -s' < ci/deploy.sh
